shariff_backend.settings:
  type: config_object
  label: 'Shariff backend settings'
  mapping:
    cache_ttl:
      typ: integer
      label: 'Share count cache TTL'
    facebook_app_id:
      type: string
      label: 'Facebook application ID'
    facebook_app_secret:
      type: string
      label: 'Facebook application client secret'
    base_domain:
      type: string
      label: 'Base domain of production instance'
    simulate_counts:
      type: boolean
      label: 'Indicate if the counts should be simulated.'